# TypeScript Server (Default)
name = "capinrs-server"
main = "typescript/src/server/index.ts"
compatibility_date = "2025-09-30"

[durable_objects]
bindings = [
	{ name = "CAPNWEB", class_name = "CapnWebDurable" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CapnWebDurable"]

[dev]
port = 8787
local_protocol = "http"

# Fill these in before deploying
# account_id = "your-account-id"
# routes = ["example.com/*"]
# workers_dev = true

# Rust WASM Server
[env.wasm]
name = "capinrs-wasm-server"
main = "typescript/src/wasm-server/index.ts"
compatibility_date = "2025-09-30"

[env.wasm.durable_objects]
bindings = [
	{ name = "CAPNWEB", class_name = "CapnWebDurable" }
]

[[env.wasm.migrations]]
tag = "v1"
new_sqlite_classes = ["CapnWebDurable"]

[env.wasm.dev]
port = 8788
local_protocol = "http"
