name = "capinrs-server"
main = "worker/src/index.ts"
compatibility_date = "2025-09-30"

[durable_objects]
bindings = [
	{ name = "CAPNWEB", class_name = "CapnWebDurable" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CapnWebDurable"]

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[dev]
port = 8787
local_protocol = "http"

# Fill these in before deploying
# account_id = "your-account-id"
# routes = ["example.com/*"]
# workers_dev = true
