name = "capinrs-server"
main = "typescript/src/server/index.ts"
compatibility_date = "2025-09-30"

[durable_objects]
bindings = [
	{ name = "CAPNWEB", class_name = "CapnWebDurable" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CapnWebDurable"]

# Removed WASM rules since we're now using pure TypeScript

[dev]
port = 8787
local_protocol = "http"

# Fill these in before deploying
# account_id = "your-account-id"
# routes = ["example.com/*"]
# workers_dev = true
